name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

              
      - name: debug env
        run: |
          echo "BASE_URL: $BASE_URL"
          echo "API_URL: $API_URL"
          echo "USER: $USER"
          echo "PASSWORD: $PASSWORD"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_URL: ${{ secrets.API_URL }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}    

      - name: Validate secrets
        run: |
          if [ -z "$USER" ]; then echo "USER is empty"; exit 1; fi
          if [ -z "$PASSWORD" ]; then echo "PASSWORD is empty"; exit 1; fi
          if [ -z "$API_URL" ]; then echo "API_URL is empty"; exit 1; fi
        env:
          API_URL: ${{ secrets.API_URL }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Run Cypress tests
        run: npx cypress run
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_URL: ${{ secrets.API_URL }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
